"""
Django settings for pigeon project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import dj_database_url
import os
import environ
import sys
from django.db import connection
env = environ.Env()
environ.Env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='django-insecure-q2%y#+z%-m5c*!&t%73twmvttt7x86!1)#w3_356k4nbhe_1)v')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG', default=True)

if DEBUG:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'pigeon', '0.0.0.0']
else:
    ALLOWED_HOSTS = ['pigeon.com', 'www.pigeon.com']
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'users.apps.UsersConfig',
    'users',
    'messenger.apps.MessengerConfig',
    'channels',
    'notifications',
    'corsheaders',
    'django_otp',
    'django_otp.plugins.otp_static',
    'django_otp.plugins.otp_totp',
    'two_factor',
    'two_factor.plugins.phonenumber',
    'rest_framework',
    'pigeon',
]

ASGI_APPLICATION = 'pigeon.asgi.application'

# Redis настройки - использовать только если есть REDIS_URL
REDIS_URL = os.environ.get('REDIS_URL')

if REDIS_URL:  # Если есть Redis URL (например, от Redis Cloud)
    # Настройки каналов для WebSocket
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [REDIS_URL],
                "channel_capacity": {
                    "http.request": 200,
                    "http.response!*": 100,
                },
            },
        }
    }
    
    # Настройки Redis для кэша и сессий
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
                "CONNECTION_POOL_KWARGS": {
                    "ssl_cert_reqs": None,
                    "decode_responses": True
                }
            }
        }
    }
    
    # Используем Redis для сессий
    SESSION_ENGINE = "django.contrib.sessions.backends.cache"
    SESSION_CACHE_ALIAS = "default"
else:
    # Для локальной разработки используем InMemoryChannelLayer
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer"
        }
    }
    
    # Локальные настройки для разработки
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "unique-snowflake",
        }
    }
    
    # Используем файловую систему для сессий
    SESSION_ENGINE = "django.contrib.sessions.backends.file"
    SESSION_FILE_PATH = os.path.join(BASE_DIR, 'sessions')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "http://pigeon:8000",
    "https://pigeon-messenger-django.onrender.com",
]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'sec-websocket-protocol',
    'sec-websocket-key',
    'sec-websocket-version',
    'sec-websocket-extensions',
]

ROOT_URLCONF = 'pigeon.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
            BASE_DIR / 'pigeon/templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'builtins': [
                'django.templatetags.static'
            ],
        },
    },
]

WSGI_APPLICATION = 'pigeon.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DB_NAME', default='pigeon'),
        'USER': env('DB_USER', default='postgres'),
        'PASSWORD': env('DB_PASSWORD', default='Qwerty1234'),
        'HOST': env('DB_HOST', default='localhost'),
        'PORT': env('DB_PORT', default='5432'),
        'OPTIONS': {
            'client_encoding': 'UTF8',
            'options': '-c lc_messages=en_US.UTF-8',
        },
    }
}

AUTH_USER_MODEL = 'users.CustomUser'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Дополнительные настройки безопасности
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'
SECURE_CONTENT_TYPE_NOSNIFF = True

# Логирование
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}

LOGIN_URL = 'login' 
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = '/'
CSRF_USE_SESSIONS = True

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = env('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = env.int('EMAIL_PORT', default=587)
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')

# Render.com specific
if 'RENDER' in os.environ:
    DEBUG = False
    ALLOWED_HOSTS = ['.onrender.com', 'localhost', '127.0.0.1']
    
    # Используем dj_database_url только на Render
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),
            conn_max_age=600,
            ssl_require=True
        )
    }
    
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
    
    # Убедитесь что whitenoise в начале middleware
    MIDDLEWARE = [
        'django.middleware.security.SecurityMiddleware',
        'whitenoise.middleware.WhiteNoiseMiddleware',
        'django.contrib.sessions.middleware.SessionMiddleware',
        'corsheaders.middleware.CorsMiddleware',
        'django.middleware.common.CommonMiddleware',
        'django.middleware.csrf.CsrfViewMiddleware',
        'django.contrib.auth.middleware.AuthenticationMiddleware',
        'django.contrib.messages.middleware.MessageMiddleware',
        'django.middleware.clickjacking.XFrameOptionsMiddleware',
    ]
    
    # Если нет Redis на Render, используем файловые сессии
    if not REDIS_URL:
        SESSION_ENGINE = "django.contrib.sessions.backends.file"
        SESSION_FILE_PATH = os.path.join(BASE_DIR, 'sessions')
        
        # Создаем директорию для сессий если не существует
        try:
            os.makedirs(SESSION_FILE_PATH, exist_ok=True)
        except Exception as e:
            print(f"Warning: Could not create session directory: {e}")
else:
    # Локальная разработка - добавляем директорию static
    STATICFILES_DIRS = [
        BASE_DIR / 'static',
    ]

# Создаем директорию для сессий если не существует (для локальной разработки)
if SESSION_ENGINE == "django.contrib.sessions.backends.file":
    try:
        os.makedirs(SESSION_FILE_PATH, exist_ok=True)
    except Exception as e:
        print(f"Warning: Could not create session directory: {e}")

# Создаем необходимые директории при запуске
def ensure_directories():
    """Создает необходимые директории если они не существуют"""
    directories = [
        STATIC_ROOT,
        MEDIA_ROOT,
    ]
    
    if 'SESSION_FILE_PATH' in locals():
        directories.append(SESSION_FILE_PATH)
    
    for directory in directories:
        try:
            os.makedirs(directory, exist_ok=True)
        except Exception as e:
            print(f"Warning: Could not create directory {directory}: {e}")

# Вызываем создание директорий
ensure_directories()

def check_and_create_tables():
    """Проверяет и создает таблицы при необходимости"""
    if 'runserver' in sys.argv or 'gunicorn' in sys.argv:
        print("🔍 Проверка состояния базы данных...")
        try:
            from django.db import connection
            with connection.cursor() as cursor:
                # Проверяем существование таблицы users_customuser
                cursor.execute("SELECT EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'users_customuser')")
                exists = cursor.fetchone()[0]
                
                if not exists:
                    print("⚠️ Таблица users_customuser не существует. Запуск миграций...")
                    from django.core.management import execute_from_command_line
                    execute_from_command_line(['manage.py', 'makemigrations', 'users', '--noinput'])
                    execute_from_command_line(['manage.py', 'migrate', 'users', '--noinput'])
                    print("✅ Миграции пользователей применены")
                    
                # Проверяем другие важные таблицы
                for table in ['auth_user', 'django_content_type', 'django_session']:
                    cursor.execute(f"SELECT EXISTS (SELECT FROM information_schema.tables WHERE table_name = '{table}')")
                    if not cursor.fetchone()[0]:
                        print(f"⚠️ Таблица {table} не существует. Запуск миграций...")
                        execute_from_command_line(['manage.py', 'migrate', 'auth', '--noinput'])
                        execute_from_command_line(['manage.py', 'migrate', 'contenttypes', '--noinput'])
                        execute_from_command_line(['manage.py', 'migrate', 'sessions', '--noinput'])
                        break
                        
        except Exception as e:
            print(f"⚠️ Ошибка при проверке базы данных: {e}")

# Вызываем проверку при импорте настроек
check_and_create_tables()

def emergency_auth_fix():
    """Экстренное решение для аутентификации без таблицы"""
    if 'runserver' in sys.argv or 'gunicorn' in sys.argv:
        print("🔧 Проверка аварийной аутентификации...")
        try:
            with connection.cursor() as cursor:
                cursor.execute("SELECT EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'users_customuser')")
                if not cursor.fetchone()[0]:
                    print("⚠️ Таблица users_customuser не существует!")
                    print("💡 Включен аварийный режим аутентификации")
                    
                    # Патчим стандартный бэкенд аутентификации
                    from django.contrib.auth.backends import ModelBackend
                    from django.contrib.auth import get_user_model
                    
                    class EmergencyModelBackend(ModelBackend):
                        def authenticate(self, request, username=None, password=None, **kwargs):
                            try:
                                return super().authenticate(request, username, password, **kwargs)
                            except Exception as e:
                                # Если таблицы нет, позволяем вход с дефолтными учетками
                                if username == 'admin' and password == 'admin123':
                                    print(f"⚡ Аварийный вход пользователя: {username}")
                                    User = get_user_model()
                                    user = User()
                                    user.pk = 1
                                    user.username = 'admin'
                                    user.is_staff = True
                                    user.is_superuser = True
                                    user.is_active = True
                                    user._password = '!admin123'
                                    return user
                                return None
                    
                    # Заменяем стандартный бэкенд
                    AUTHENTICATION_BACKENDS = ['pigeon.settings.EmergencyModelBackend']
        except Exception as e:
            print(f"⚠️ Ошибка при проверке таблицы: {e}")

# Вызываем проверку
emergency_auth_fix()
